---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Ansible version check
  - ansible-playbook --version

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
