---
- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Create iptables configuration
  template: >
    src=iptables.j2
    dest={{ iptables_configuration }}
    owner=root
    group=root
    mode=0600
  register: config_result
  notify: restart iptables

- name: Ensure iptables is started and enabled on boot
  service: name={{ iptables_service_name }} state=started enabled=yes
  changed_when: False
